export default {
  'arvoll': {
    title: 'Årvoll Torg, Oslo',
    preview: '/arvoll.jpg',
    link: 'https://aarvolltorg.no/new-homes-single-project/til-salgs/boligvelger/601',
    views: [
      'https://plyo.io/senfu/panorama/scene.html?name=arvollveien-Takterrasse-North_v01&showScenePanel=false&showTitle=false&autoLoad=false',
      'https://plyo.io/senfu/panorama/scene.html?name=arvollveien-Takterrasse-East_v01&showScenePanel=false&showTitle=false&autoLoad=false',
      'https://plyo.io/senfu/panorama/scene.html?name=arvollveien-L201_v01&showScenePanel=false&showTitle=false&autoLoad=false',
      'https://plyo.io/senfu/panorama/scene.html?name=arvollveien-L601_v01&showScenePanel=false&showTitle=false&autoLoad=false',
      'https://plyo.io/senfu/panorama/scene.html?name=arvollveien-L501_v01&showScenePanel=false&showTitle=false&autoLoad=false',
      'https://plyo.io/senfu/panorama/scene.html?name=arvollveien-L205_v01&showScenePanel=false&showTitle=false&autoLoad=false',
      'https://plyo.io/senfu/panorama/scene.html?name=arvollveien-L301_v01&showScenePanel=false&showTitle=false&autoLoad=false',
      'https://plyo.io/senfu/panorama/scene.html?name=arvollveien-L401_v01&showScenePanel=false&showTitle=false&autoLoad=false',
    ],
  },
  'fyrstikkbakken': {
    title: 'Fyrstikkbakken 14, Oslo',
    preview: '/fyrstikkbakken.webp',
    link: 'https://fyrstikkbakken14.no/vare-boliger/fyrstikkbakken-14/til-salgs/boligvelger/bygg-a/a-903',
    views: [
      'https://plyo.io/senfu/panorama/scene.html?name=f14-000&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
      'https://plyo.io/senfu/panorama/scene.html?name=f14-003&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
      'https://plyo.io/senfu/panorama/scene.html?name=f14-005&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
      'https://plyo.io/senfu/panorama/scene.html?name=f14-006&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
      'https://plyo.io/senfu/panorama/scene.html?name=f14-009&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
      'https://plyo.io/senfu/panorama/scene.html?name=f14-011&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
      'https://plyo.io/senfu/panorama/scene.html?name=f14-012&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
      'https://plyo.io/senfu/panorama/scene.html?name=f14-015&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
    ],
  },
  'lachmanns': {
    title: 'Lachmanns Vei 2, Oslo',
    preview: '/lachmanns.jpg',
    link: 'https://lp2.no/new-homes-single-project/til-salgs/boligvelger/a3',
    views: [
      'https://plyo.io/senfu/panorama/scene.html?name=lachmannsvei2-a1_Day&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
      'https://plyo.io/senfu/panorama/scene.html?name=lachmannsvei2-a1_Night&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
      'https://plyo.io/senfu/panorama/scene.html?name=lachmannsvei2-a2_Day&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
      'https://plyo.io/senfu/panorama/scene.html?name=lachmannsvei2-a2_Night&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
      'https://plyo.io/senfu/panorama/scene.html?name=lachmannsvei2-b1_Day-v2&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
      'https://plyo.io/senfu/panorama/scene.html?name=lachmannsvei2-b1_Night&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
      'https://plyo.io/senfu/panorama/scene.html?name=lachmannsvei2-c3_Day&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
      'https://plyo.io/senfu/panorama/scene.html?name=lachmannsvei2-c3_Night&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
    ],
  },
  'lyngheiane': {
    title: 'Lyngheiane, Knarvik',
    preview: '/lyngheiane.jpg',
    link: 'https://lyngheianebolig.no/til-salgs/boligvelger/bygg-b2/b2-315',
    views: [
      'https://plyo.io/senfu/panorama/scene.html?name=lyngheiane-B405_v01&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
      'https://plyo.io/senfu/panorama/scene.html?name=lyngheiane-B303_v01&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
      'https://plyo.io/senfu/panorama/scene.html?name=lyngheiane-B306_v01&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
      'https://plyo.io/senfu/panorama/scene.html?name=lyngheiane-B401_v01&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
      'https://plyo.io/senfu/panorama/scene.html?name=lyngheiane-B402_v01&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
      'https://3destate.viewin360.co/share/N3d6S?logo=-1&info=0&fs=1&vr=1&sd=1&initload=0&thumbs=1&ovd=3destate.viewin360.co',
      'https://3destate.viewin360.co/share/N31jh?logo=-1&info=0&fs=1&vr=1&sd=1&initload=0&thumbs=1&ovd=3destate.viewin360.co',
    ],
  },
  'sprohavn': {
    title: 'Spro havn, Spro',
    preview: '/sprohavn.jpg',
    link: 'https://sprohavn.no/vare-boliger/salgstrinn-2/b-702',
    views: [
      'https://plyo.io/senfu/panorama/scene.html?name=spro-havn-b2-011&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
      'https://plyo.io/senfu/panorama/scene.html?name=spro-havn-b2-074&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
      'https://plyo.io/senfu/panorama/scene.html?name=spro-havn-024&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
      'https://plyo.io/senfu/panorama/scene.html?name=spro-havn-b1-v3-028&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
      'https://plyo.io/senfu/panorama/scene.html?name=spro-havn-035&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
      'https://plyo.io/senfu/panorama/scene.html?name=spro-havn-012&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
      'https://plyo.io/senfu/panorama/scene.html?name=spro-havn-b2-028&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
      'https://plyo.io/senfu/panorama/scene.html?name=spro-havn-b2-067&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
    ],
  },
  'rolvsrud': {
    title: 'Rolvsrud Arena, Lørenskog',
    preview: '/rolvsrud.webp',
    link: 'https://rolvsrudarena.no/prosjektside/boligvelger/hus1/1-1002',
    views: [
     'https://plyo.io/senfu/panorama/scenes.html?id=c84fceb3-554e-41f3-9e57-4dfe3ec1c323&initialScene=rolvsrud-b2-v1-902&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
     'https://plyo.io/senfu/panorama/scenes.html?id=817e54cb-9622-43af-8a2d-441bf5801e1a&initialScene=rolvsrud-b2-v1-802&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
     'https://plyo.io/senfu/panorama/scenes.html?id=acaf3bc9-1d59-4d8b-9bde-4f740fdc1fa8&initialScene=rolvsrud-b1-v2-1003&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
     'https://plyo.io/senfu/panorama/scenes.html?id=27349d09-1c10-411f-b6d9-bafc961dcaf0&initialScene=rolvsrud-b1-v2-1004&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
     'https://plyo.io/senfu/panorama/scenes.html?id=eadcb5bc-0cd4-47b8-aa65-293ae984b226&initialScene=rolvsrud-b2-v1-1001&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
     'https://plyo.io/senfu/panorama/scenes.html?id=7ab87cc9-5e98-4ce8-81ff-997c45faf814&initialScene=rolvsrud-b2-v1-1002&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
     'https://plyo.io/senfu/panorama/scenes.html?id=817e54cb-9622-43af-8a2d-441bf5801e1a&initialScene=rolvsrud-b2-v1-802&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
     'https://plyo.io/senfu/panorama/scenes.html?id=e65fe83a-8ec2-4278-b929-c02d0caa6008&initialScene=rolvsrud-b2-v1-703&showScenePanel=false&showTitle=false&autoLoad=false&pano=true',
    ],
  },
}
